---
title: "HW01_Gapminder"
output: github_document
---

```{r load}
library(gapminder)
library(tibble)
library(DT)
library(dplyr)
```

From the package gapminder, there is a built-in tibble called gapminder, which I'll be exploring here using dyplr 


First, lets see how many countries are in this tibble: 
```{r}
Count <- (count(gapminder,country))
print(nrow(Count))
```



Another way you could count the countries:
```{r}
countries <- gapminder$country
countries <- (unique(countries))
print(length(countries))
```


What is the average life expectancy in Canada throughout all years recorded? 

```{r}
life_expect <- select(gapminder, country, lifeExp)
life_expect <- filter(gapminder, country=='Canada', !is.na(lifeExp))
average <- mean(life_expect$lifeExp)
  print(mean(average))
```

Which country has the highest population in 2002, and what was the population?

```{r}
population <- select(gapminder, year, country, pop)
population <- filter(population,year==2002)
population <- arrange(population, desc(pop))
Country <- population$country
Country <- Country[1]
max_pop <- population$pop
max_pop <- max_pop[1]
print(Country)
print(max_pop)

```

